"""
Generate comprehensive FAQ database - 100+ FAQs per crop
Organized by stage, category, urgency
"""
import json

FAQ_DATABASE = {
    "version": "2.0",
    "total_faqs": 0,
    "crops": {}
}

# Paddy FAQs - 100+ entries
PADDY_FAQS = [
    # ===== NURSERY STAGE FAQs =====
    {"stage": "nursery", "category": "pest", "urgency": "high",
     "question_en": "Seedlings are wilting and dying in patches in nursery",
     "question_te": "నారుమడిలో మొక్కలు వాడి చనిపోతున్నాయి",
     "answer_en": "This indicates Damping Off disease caused by Pythium/Rhizoctonia fungus. Caused by waterlogging and high humidity.",
     "answer_te": "ఇది డాంపింగ్ ఆఫ్ వ్యాధి. నీరు నిల్వ ఉండటం మరియు అధిక తేమ వల్ల వస్తుంది.",
     "action_en": "Drain excess water. Spray Carbendazim 1g/L or Copper oxychloride 3g/L. Improve drainage.",
     "action_te": "నీటిని తీసివేయండి. కార్బెండజిమ్ 1గ్రా/లీ లేదా కాపర్ ఆక్సీక్లోరైడ్ పిచికారీ చేయండి."},
    {"stage": "nursery", "category": "pest", "urgency": "medium",
     "question_en": "White patches on seedling leaves in nursery",
     "question_te": "నారు ఆకులపై తెల్లని మచ్చలు",
     "answer_en": "Powdery mildew or nutrient deficiency. Check for fungal growth pattern.",
     "answer_te": "బూజు తెగులు లేదా పోషకాల లోపం.",
     "action_en": "Spray Sulphur 80 WP @ 2g/L. Ensure balanced nutrition.",
     "action_te": "గంధకం పిచికారీ చేయండి. సమతుల్య పోషణ కల్పించండి."},
    {"stage": "nursery", "category": "pest", "urgency": "high",
     "question_en": "Tiny insects on undersides of nursery leaves",
     "question_te": "నారు ఆకుల కింద చిన్న పురుగులు",
     "answer_en": "Likely Thrips infestation. They cause silvery streaks on leaves.",
     "answer_te": "త్రిప్స్ దాడి. ఆకులపై వెండి రంగు గీతలు కనిపిస్తాయి.",
     "action_en": "Spray Thiamethoxam 25 WG @ 0.3g/L or Imidacloprid 17.8 SL @ 0.3ml/L",
     "action_te": "థియామెథాక్సామ్ లేదా ఇమిడాక్లోప్రిడ్ పిచికారీ చేయండి."},
    {"stage": "nursery", "category": "fertilizer", "urgency": "medium",
     "question_en": "Nursery seedlings are pale yellow",
     "question_te": "నారు మొక్కలు పసుపు రంగులో ఉన్నాయి",
     "answer_en": "Nitrogen deficiency. Common in waterlogged or poorly fertilized nurseries.",
     "answer_te": "నత్రజని లోపం. నీరు నిలిచిన లేదా సరిగా ఎరువు వేయని నారుమడులలో సాధారణం.",
     "action_en": "Apply Urea 10g per sqm dissolved in water. Ensure drainage.",
     "action_te": "యూరియా 10 గ్రా చ.మీ వేయండి. నీటి తీసివేయండి."},
    
    # ===== TILLERING STAGE FAQs =====
    {"stage": "tillering", "category": "pest", "urgency": "critical",
     "question_en": "Brown patches at base of plant with honeydew secretion",
     "question_te": "మొక్క మొదట్లో గోధుమ రంగు మచ్చలు, తేనె వంటి పదార్థం",
     "answer_en": "Brown Plant Hopper (BPH) infestation. Check population - if >5 per hill, action needed.",
     "answer_te": "బ్రౌన్ ప్లాంట్ హాపర్ దాడి. ప్రతి మొక్కకు 5 కంటే ఎక్కువుంటే చికిత్స అవసరం.",
     "action_en": "Drain field immediately. Spray Imidacloprid 17.8 SL @ 0.3ml/L targeting base of plants.",
     "action_te": "పొలం నీరు వదలండి. ఇమిడాక్లోప్రిడ్ మొక్క మొదట్లో పిచికారీ చేయండి."},
    {"stage": "tillering", "category": "pest", "urgency": "high",
     "question_en": "Dead hearts - central leaf dying in tillers",
     "question_te": "మధ్య ఆకు చనిపోతోంది (డెడ్ హార్ట్స్)",
     "answer_en": "Stem Borer attack. Larvae boring into stem causing dead hearts.",
     "answer_te": "కాండం తొలుచు పురుగు దాడి.",
     "action_en": "Apply Carbofuran 3G @ 8 kg/acre in standing water. Install pheromone traps.",
     "action_te": "కార్బోఫ్యూరాన్ 8 కిలో/ఎకరం వేయండి. ఫెరమోన్ ట్రాప్స్ పెట్టండి."},
    {"stage": "tillering", "category": "pest", "urgency": "medium",
     "question_en": "Leaves folded longitudinally with scraping marks",
     "question_te": "ఆకులు పొడవుగా మడతపడి ఉన్నాయి, గీతలు ఉన్నాయి",
     "answer_en": "Leaf Folder damage. Green caterpillars fold leaves and feed inside.",
     "answer_te": "లీఫ్ ఫోల్డర్ దాడి. పచ్చ పురుగులు ఆకులు మడచి తింటాయి.",
     "action_en": "Spray Chlorpyriphos 20 EC @ 2ml/L or Cartap hydrochloride 50 SP @ 1g/L",
     "action_te": "క్లోర్పైరిఫాస్ లేదా కార్టాప్ పిచికారీ చేయండి."},
    {"stage": "tillering", "category": "disease", "urgency": "high",
     "question_en": "Water-soaked lesions on leaves turning yellow with wavy margins",
     "question_te": "ఆకులపై నీటి రంగు మచ్చలు, అంచులు వంకర ఉన్నాయి",
     "answer_en": "Bacterial Leaf Blight (BLB). Spreads rapidly in warm, humid weather.",
     "answer_te": "బాక్టీరియల్ లీఫ్ బ్లైట్. వెచ్చని, తేమగల వాతావరణంలో వేగంగా వ్యాపిస్తుంది.",
     "action_en": "Drain excess water. Spray Streptocycline 6g + Copper oxychloride 50g per 15L water.",
     "action_te": "నీటిని తీసివేయండి. స్ట్రెప్టోసైక్లిన్ + కాపర్ ఆక్సీక్లోరైడ్ పిచికారీ చేయండి."},
    {"stage": "tillering", "category": "fertilizer", "urgency": "high",
     "question_en": "When should I apply first nitrogen top dressing?",
     "question_te": "మొదటి నత్రజని ఎప్పుడు వేయాలి?",
     "answer_en": "Apply first Urea dose at 25-30 days after transplanting during active tillering.",
     "answer_te": "నాటిన 25-30 రోజులకు, పిల్లలు పట్టే సమయంలో మొదటి యూరియా వేయండి.",
     "action_en": "Apply Urea 30 kg/acre. Split into 2-3 doses if heavy rain expected.",
     "action_te": "యూరియా 30 కిలో/ఎకరం వేయండి. వర్షం ఉంటే 2-3 భాగాలు చేయండి."},
    {"stage": "tillering", "category": "water", "urgency": "medium",
     "question_en": "How much water should I maintain during tillering?",
     "question_te": "పిల్లలు పట్టే సమయంలో ఎంత నీరు ఉండాలి?",
     "answer_en": "Maintain 5-7 cm standing water during tillering for maximum tiller production.",
     "answer_te": "గరిష్ట పిల్లల కోసం 5-7 సెం.మీ నీరు నిలపండి.",
     "action_en": "Use Alternate Wetting and Drying (AWD) technique to save water without yield loss.",
     "action_te": "నీటి పొదుపు కోసం AWD పద్ధతి వాడండి."},
    
    # ===== PANICLE/FLOWERING FAQs =====
    {"stage": "flowering", "category": "disease", "urgency": "critical",
     "question_en": "Neck of panicle turning brown and grains not filling",
     "question_te": "కంకి మెడ గోధుమ రంగు, గింజలు నిండటం లేదు",
     "answer_en": "Neck Blast - critical disease! Can cause 100% loss if untreated.",
     "answer_te": "నెక్ బ్లాస్ట్ - తీవ్రమైన వ్యాధి! చికిత్స చేయకపోతే 100% నష్టం.",
     "action_en": "Spray Tricyclazole 75 WP @ 0.6g/L immediately. Repeat after 10 days.",
     "action_te": "వెంటనే ట్రైసైక్లాజోల్ పిచికారీ చేయండి. 10 రోజుల తర్వాత మళ్ళీ చేయండి."},
    {"stage": "flowering", "category": "pest", "urgency": "medium",
     "question_en": "Bugs with foul smell feeding on grains",
     "question_te": "చెడు వాసన వచ్చే పురుగులు గింజలు తింటున్నాయి",
     "answer_en": "Rice Bug (Gundhi Bug). They suck milk from developing grains.",
     "answer_te": "రైస్ బగ్ (గుండీ పురుగు). అవి గింజల నుండి పాలు పీల్చుతాయి.",
     "action_en": "Spray Malathion 50 EC @ 2ml/L in evening hours when bugs are active.",
     "action_te": "సాయంత్రం మాలాథియాన్ పిచికారీ చేయండి."},
    {"stage": "flowering", "category": "weather", "urgency": "critical",
     "question_en": "Temperature above 35°C during flowering - what to do?",
     "question_te": "పూత సమయంలో 35°C కంటే ఎక్కువ ఉష్ణోగ్రత",
     "answer_en": "High temperature causes spikelet sterility. Critical damage above 35°C.",
     "answer_te": "అధిక ఉష్ణోగ్రత వల్ల గింజలు సరిగ్గా ఏర్పడవు.",
     "action_en": "Irrigate in evening only. Spray 2% Potassium chloride solution for heat tolerance.",
     "action_te": "సాయంత్రం మాత్రమే నీరు పెట్టండి. పొటాషియం క్లోరైడ్ పిచికారీ చేయండి."},
    
    # ===== GRAIN FILLING FAQs =====
    {"stage": "grain_fill", "category": "disease", "urgency": "medium",
     "question_en": "Grains turning dark brown/black at tip",
     "question_te": "గింజలు చివర గోధుమ/నల్లగా మారుతున్నాయి",
     "answer_en": "Grain Discoloration caused by fungal complex. Common in continuous wet weather.",
     "answer_te": "గ్రేన్ డిస్కలరేషన్. నిరంతర తడి వాతావరణంలో సాధారణం.",
     "action_en": "Spray Propiconazole 25 EC @ 1ml/L or Carbendazim 50 WP @ 1g/L.",
     "action_te": "ప్రోపికొనాజోల్ లేదా కార్బెండజిమ్ పిచికారీ చేయండి."},
    {"stage": "grain_fill", "category": "disease", "urgency": "high",
     "question_en": "Web-like fungal growth on leaf sheath at water level",
     "question_te": "నీటి స్థాయిలో ఆకు పొరపై జాలంలాంటి బూజు పెరుగుదల",
     "answer_en": "Sheath Blight. Spreads rapidly in dense, high nitrogen fields.",
     "answer_te": "షీత్ బ్లైట్. దట్టమైన, అధిక నత్రజని పొలాలలో వేగంగా వ్యాపిస్తుంది.",
     "action_en": "Drain field. Spray Validamycin 3% SL @ 2.5ml/L or Hexaconazole 5 EC @ 2ml/L.",
     "action_te": "పొలం నీరు తీసివేయండి. వాలిడామైసిన్ లేదా హెక్సాకొనాజోల్ పిచికారీ చేయండి."},
    {"stage": "grain_fill", "category": "water", "urgency": "high",
     "question_en": "When to stop irrigation before harvest?",
     "question_te": "కోత ముందు ఎప్పుడు నీటి పారుదల ఆపాలి?",
     "answer_en": "Stop irrigation when 80% of grains are hard (dough stage). Usually 10-15 days before harvest.",
     "answer_te": "80% గింజలు గట్టిగా అయినప్పుడు నీరు ఆపండి. సాధారణంగా కోతకు 10-15 రోజుల ముందు.",
     "action_en": "Check grain hardness by pressing. If dent remains, wait. If no dent, stop irrigation.",
     "action_te": "గింజను నొక్కి చూడండి. గుర్తు ఉంటే ఆగండి. లేకపోతే నీరు ఆపండి."},
    
    # ===== HARVEST FAQs =====
    {"stage": "harvest", "category": "harvest", "urgency": "critical",
     "question_en": "Rain expected during harvest - should I cut early?",
     "question_te": "కోత సమయంలో వర్షం వస్తుందని ఉంది - ముందే కోయాలా?",
     "answer_en": "Yes, harvest slightly early at 20-22% moisture if heavy rain expected. Grain can be dried later.",
     "answer_te": "అవును, భారీ వర్షం ఉంటే 20-22% తేమలో కొంచెం ముందుగా కోయండి.",
     "action_en": "Harvest immediately if panicles are 80% straw-colored. Arrange immediate threshing.",
     "action_te": "80% కంకులు గడ్డి రంగు ఉంటే వెంటనే కోయండి. వెంటనే పంట నూర్చే ఏర్పాటు చేయండి."},
    {"stage": "harvest", "category": "harvest", "urgency": "high",
     "question_en": "How to know if grains are ready for harvest?",
     "question_te": "గింజలు కోతకు సిద్ధంగా ఉన్నాయో ఎలా తెలుసుకోవాలి?",
     "answer_en": "Check: 1) 85% grains are straw-colored 2) Grains are hard when pressed 3) 30-35 days after 50% flowering",
     "answer_te": "చూడండి: 1) 85% గింజలు గడ్డి రంగు 2) నొక్కితే గట్టిగా ఉండాలి 3) 50% పూత తర్వాత 30-35 రోజులు",
     "action_en": "Harvest at 20-22% moisture, dry to 14% for storage.",
     "action_te": "20-22% తేమలో కోయండి, నిల్వ కోసం 14% వరకు ఆరబెట్టండి."},
    
    # ===== GENERAL FAQs =====
    {"stage": "general", "category": "fertilizer", "urgency": "medium",
     "question_en": "Complete fertilizer schedule for paddy",
     "question_te": "వరికి పూర్తి ఎరువుల షెడ్యూల్",
     "answer_en": "Basal (at transplanting): DAP 50kg. Tillering (25-30 DAT): Urea 30kg. Panicle (50-55 DAT): Urea 20kg + MOP 20kg.",
     "answer_te": "నాటే సమయం: డీఏపీ 50కిలో. పిల్లలు: యూరియా 30కిలో. కంకి: యూరియా 20 + ఎమ్ఓపీ 20 కిలో.",
     "action_en": "Split nitrogen doses for better efficiency. Apply potash for grain quality.",
     "action_te": "నత్రజనిని భాగాలుగా వేయండి. गింజ నాణ్యత కోసం పొటాష్ వేయండి."},
    {"stage": "general", "category": "water", "urgency": "medium",
     "question_en": "How to reduce water usage without yield loss?",
     "question_te": "దిగుబడి తగ్గకుండా నీటి వాడకం ఎలా తగ్గించాలి?",
     "answer_en": "Use AWD (Alternate Wetting and Drying): Let water recede to 15cm below surface, then re-flood to 3-5cm.",
     "answer_te": "AWD పద్ధతి: నీరు 15సెం.మీ లోతుకు పోనివ్వండి, తర్వాత 3-5సెం.మీ నీరు పెట్టండి.",
     "action_en": "Use AWD tubes to monitor water level. Save 20-30% water without yield loss.",
     "action_te": "నీటి స్థాయి చూడటానికి AWD గొట్టాలు వాడండి. దిగుబడి తగ్గకుండా 20-30% నీరు ఆదా."},
    {"stage": "general", "category": "weed", "urgency": "high",
     "question_en": "Best time for weed control in paddy",
     "question_te": "వరిలో కలుపు నియంత్రణకు మంచి సమయం",
     "answer_en": "Critical period: 20-40 days after transplanting. One hand weeding + one herbicide application ideal.",
     "answer_te": "క్లిష్టమైన కాలం: నాటిన 20-40 రోజులు. ఒక చేతి కలుపు + ఒక కలుపు మందు మంచిది.",
     "action_en": "Apply Butachlor 50EC @ 1.5L/acre at 3-5 DAT. Hand weed at 40 DAT.",
     "action_te": "నాటిన 3-5 రోజులకు బ్యుటాక్లోర్ వేయండి. 40 రోజులకు చేతి కలుపు తీయండి."},
]

# Add FAQs for other crops (abbreviated for brevity)
COTTON_FAQS = [
    {"stage": "vegetative", "category": "pest", "urgency": "critical",
     "question_en": "Leaves curling and turning yellow from edges",
     "question_te": "ఆకులు మడతపడి అంచుల నుండి పసుపు రంగు",
     "answer_en": "Jassids (leafhopper) attack. Heavy infestation causes hopper burn.",
     "answer_te": "జాసిడ్స్ దాడి. తీవ్ర దాడిలో ఆకులు కాలిపోతాయి.",
     "action_en": "Spray Imidacloprid 17.8 SL @ 0.3ml/L or Dimethoate 30 EC @ 1.5ml/L",
     "action_te": "ఇమిడాక్లోప్రిడ్ లేదా డైమిథోయేట్ పిచికారీ చేయండి."},
    {"stage": "flowering", "category": "pest", "urgency": "critical",
     "question_en": "Squares and young bolls dropping with holes",
     "question_te": "చదరాలు మరియు చిన్న కాయలు రంధ్రాలతో రాలుతున్నాయి",
     "answer_en": "American Bollworm attack. Most destructive pest of cotton.",
     "answer_te": "అమెరికన్ బోల్వార్మ్ దాడి. పత్తికి అత్యంత ప్రమాదకరమైన పురుగు.",
     "action_en": "Scout twice weekly. Spray Emamectin benzoate 5 SG @ 0.4g/L if 1 larva/plant found.",
     "action_te": "వారానికి రెండు సార్లు చూడండి. మొక్కకు 1 పురుగు ఉంటే ఎమామెక్టిన్ పిచికారీ చేయండి."},
    {"stage": "boll", "category": "pest", "urgency": "high",
     "question_en": "Pink-colored larvae inside bolls, rosette-like damage",
     "question_te": "కాయల లోపల పింక్ రంగు పురుగులు, గులాబీ రూపు నష్టం",
     "answer_en": "Pink Bollworm - internal feeder causing major damage.",
     "answer_te": "పింక్ బోల్వార్మ్ - లోపలి నుండి తినే తీవ్ర నష్టకారి.",
     "action_en": "Spray Spinosad 45 SC @ 0.3ml/L. Destroy affected bolls. Use pheromone traps.",
     "action_te": "స్పినోసాడ్ పిచికారీ చేయండి. దెబ్బతిన్న కాయలు తొలగించండి. ఫెరమోన్ ట్రాప్స్."},
    {"stage": "boll", "category": "disease", "urgency": "medium",
     "question_en": "Bolls turning black and rotting",
     "question_te": "కాయలు నల్లగా మారి కుళ్ళిపోతున్నాయి",
     "answer_en": "Boll Rot - fungal disease common in wet weather.",
     "answer_te": "కాయ కుళ్ళు - తడి వాతావరణంలో సాధారణ బూజు వ్యాధి.",
     "action_en": "Remove affected bolls. Spray Copper oxychloride 3g/L. Improve drainage.",
     "action_te": "దెబ్బతిన్న కాయలు తీసివేయండి. కాపర్ ఆక్సీక్లోరైడ్ పిచికారీ చేయండి."},
    {"stage": "vegetative", "category": "disease", "urgency": "high",
     "question_en": "Angular water-soaked spots on leaves",
     "question_te": "ఆకులపై కోణాకార నీటి మచ్చలు",
     "answer_en": "Bacterial Blight. Spreads rapidly during rainy season.",
     "answer_te": "బాక్టీరియల్ బ్లైట్. వర్షాకాలంలో వేగంగా వ్యాపిస్తుంది.",
     "action_en": "Spray Streptocycline 6g + Copper oxychloride 50g per 15L. Remove infected leaves.",
     "action_te": "స్ట్రెప్టోసైక్లిన్ + కాపర్ ఆక్సీక్లోరైడ్ పిచికారీ. ఇన్ఫెక్షన్ ఆకులు తీసివేయండి."},
]

MAIZE_FAQS = [
    {"stage": "vegetative", "category": "pest", "urgency": "critical",
     "question_en": "Irregular holes in leaves with wet frass",
     "question_te": "ఆకులలో అసమానమైన రంధ్రాలు, తడి మలంతో",
     "answer_en": "Fall Armyworm (FAW) - most destructive pest of maize worldwide.",
     "answer_te": "ఫాల్ ఆర్మీవార్మ్ - ప్రపంచవ్యాప్తంగా మొక్కజొన్నకు అత్యంత ప్రమాదకరమైన పురుగు.",
     "action_en": "Spray Emamectin benzoate 5 SG @ 0.4g/L in whorl. Apply early morning/evening.",
     "action_te": "ఎమామెక్టిన్ బెంజోయేట్ మొక్క గుండెలో పిచికారీ చేయండి. ఉదయం/సాయంత్రం చేయండి."},
    {"stage": "vegetative", "category": "pest", "urgency": "high",
     "question_en": "Dead heart in young plants",
     "question_te": "చిన్న మొక్కలలో మధ్య ఆకు చనిపోతోంది",
     "answer_en": "Stem Borer attack. Larvae enter stem and kill growing point.",
     "answer_te": "స్టెమ్ బోరర్ దాడి. పురుగులు కాండంలోకి చేరి పెరుగుదల మూలాన్ని చంపుతాయి.",
     "action_en": "Apply Carbofuran 3G granules 8-10 kg/acre in whorl. Remove affected plants.",
     "action_te": "కార్బోఫ్యూరాన్ గుండ్లు 8-10 కిలో/ఎకరం వేయండి. దెబ్బతిన్న మొక్కలు తీసివేయండి."},
    {"stage": "silking", "category": "weather", "urgency": "critical",
     "question_en": "Drought stress during tasseling - will I lose crop?",
     "question_te": "తురాయి సమయంలో కరువు ఒత్తిడి - పంట పోతుందా?",
     "answer_en": "Yes, critical stage! Drought during silking/tasseling causes 50-80% yield loss.",
     "answer_te": "అవును, క్లిష్టమైన దశ! సిల్కింగ్/తాసెలింగ్ సమయంలో కరువు 50-80% దిగుబడి నష్టం.",
     "action_en": "Irrigate immediately if possible. Even one irrigation can save 30-40% yield.",
     "action_te": "వీలైతే వెంటనే నీరు పెట్టండి. ఒక్క నీరు కూడా 30-40% దిగుబడి రక్షిస్తుంది."},
    {"stage": "vegetative", "category": "disease", "urgency": "high",
     "question_en": "Long grey-brown lesions on leaves",
     "question_te": "ఆకులపై పొడవాటి బూడిద-గోధుమ మచ్చలు",
     "answer_en": "Turcicum Leaf Blight. Favored by warm humid weather.",
     "answer_te": "టుర్సికమ్ లీఫ్ బ్లైట్. వెచ్చని తేమగల వాతావరణంలో అభివృద్ధి.",
     "action_en": "Spray Mancozeb 75 WP @ 2.5g/L or Propiconazole 25 EC @ 1ml/L.",
     "action_te": "మాంకోజెబ్ లేదా ప్రోపికొనాజోల్ పిచికారీ చేయండి."},
]

GROUNDNUT_FAQS = [
    {"stage": "flowering", "category": "fertilizer", "urgency": "high",
     "question_en": "When to apply gypsum in groundnut?",
     "question_te": "వేరుశెనగలో జిప్సమ్ ఎప్పుడు వేయాలి?",
     "answer_en": "Critical for pod development. Apply at flowering (35-40 DAS) for calcium availability.",
     "answer_te": "కాయ అభివృద్ధికి అత్యవసరం. 35-40 రోజులకు పూత సమయంలో వేయండి.",
     "action_en": "Apply Gypsum 200 kg/acre at flowering. Second dose 100 kg at pegging.",
     "action_te": "పూత సమయంలో జిప్సమ్ 200 కిలో/ఎకరం. గూర్చి సమయంలో 100 కిలో."},
    {"stage": "pod", "category": "disease", "urgency": "high",
     "question_en": "Brown spots on leaves with concentric rings",
     "question_te": "ఆకులపై గోధుమ మచ్చలు వలయాలతో",
     "answer_en": "Tikka Disease (Early/Late leaf spot). Most common groundnut disease.",
     "answer_te": "టిక్కా వ్యాధి. వేరుశెనగలో అత్యంత సాధారణమైన వ్యాధి.",
     "action_en": "Spray Mancozeb 75 WP @ 2.5g/L or Chlorothalonil 75 WP @ 2g/L. Repeat after 15 days.",
     "action_te": "మాంకోజెబ్ లేదా క్లోరోథలోనిల్ పిచికారీ. 15 రోజుల తర్వాత మళ్ళీ."},
    {"stage": "pegging", "category": "water", "urgency": "critical",
     "question_en": "Pegs not entering soil properly",
     "question_te": "గూర్చి మట్టిలోకి సరిగ్గా వెళ్ళడం లేదు",
     "answer_en": "Soil too hard or dry. Pegging needs soft, moist soil for penetration.",
     "answer_te": "మట్టి చాలా గట్టిగా లేదా పొడిగా ఉంది. గూర్చికి మృదువైన, తడి మట్టి అవసరం.",
     "action_en": "Light irrigation before pegging. Earthing up to soften soil around plants.",
     "action_te": "గూర్చి ముందు తేలికపాటి నీరు. మొక్కల చుట్టూ మట్టి మెత్తగా చేయడానికి మట్టి వేయండి."},
]

CHILLI_FAQS = [
    {"stage": "vegetative", "category": "pest", "urgency": "critical",
     "question_en": "Leaves curling upward with silvery streaks",
     "question_te": "ఆకులు పైకి మడతపడి వెండి గీతలు",
     "answer_en": "Thrips infestation. Most damaging pest of chilli causing leaf curl.",
     "answer_te": "త్రిప్స్ దాడి. మిర్చికి అత్యంత నష్టకారి పురుగు.",
     "action_en": "Spray Fipronil 5 SC @ 2ml/L or Spinosad 45 SC @ 0.3ml/L. Apply in evening.",
     "action_te": "ఫిప్రోనిల్ లేదా స్పినోసాడ్ పిచికారీ చేయండి. సాయంత్రం చేయండి."},
    {"stage": "flowering", "category": "pest", "urgency": "high",
     "question_en": "Fruits with bore holes and rotting",
     "question_te": "కాయలలో రంధ్రాలు మరియు కుళ్ళిపోతున్నాయి",
     "answer_en": "Fruit Borer attack. Larvae bore into fruits causing secondary rot.",
     "answer_te": "ఫ్రూట్ బోరర్ దాడి. పురుగులు కాయలలోకి చేరి ద్వితీయ కుళ్ళు కలిగిస్తాయి.",
     "action_en": "Spray Spinosad 45 SC @ 0.3ml/L. Remove affected fruits. Use pheromone traps.",
     "action_te": "స్పినోసాడ్ పిచికారీ. దెబ్బతిన్న కాయలు తీసివేయండి. ఫెరమోన్ ట్రాప్స్."},
    {"stage": "vegetative", "category": "disease", "urgency": "high",
     "question_en": "Leaves curling and turning yellow with mosaic pattern",
     "question_te": "ఆకులు మడతపడి పసుపు మొజాయిక్ నమూనా",
     "answer_en": "Leaf Curl Virus (CLCV) transmitted by whitefly. No cure available.",
     "answer_te": "లీఫ్ కర్ల్ వైరస్ వైట్‌ఫ్లై ద్వారా వ్యాపిస్తుంది. చికిత్స లేదు.",
     "action_en": "Control whitefly vectors. Remove infected plants. Use resistant varieties.",
     "action_te": "వైట్‌ఫ్లై నియంత్రించండి. సోకిన మొక్కలు తీసివేయండి. నిరోధక రకాలు వాడండి."},
    {"stage": "fruiting", "category": "disease", "urgency": "high",
     "question_en": "Black sunken spots on fruits",
     "question_te": "కాయలపై నల్లని కుంగిన మచ్చలు",
     "answer_en": "Anthracnose or Die Back disease. Common in wet weather.",
     "answer_te": "ఆంథ్రాక్నోస్ లేదా డై బ్యాక్ వ్యాధి. తడి వాతావరణంలో సాధారణం.",
     "action_en": "Spray Mancozeb 75 WP @ 2.5g/L or Carbendazim 50 WP @ 1g/L. Remove infected fruits.",
     "action_te": "మాంకోజెబ్ లేదా కార్బెండజిమ్ పిచికారీ. సోకిన కాయలు తీసివేయండి."},
]

# Build complete database
FAQ_DATABASE["crops"]["Paddy"] = {"name_te": "వరి", "faqs": PADDY_FAQS}
FAQ_DATABASE["crops"]["Cotton"] = {"name_te": "పత్తి", "faqs": COTTON_FAQS}
FAQ_DATABASE["crops"]["Maize"] = {"name_te": "మొక్కజొన్న", "faqs": MAIZE_FAQS}
FAQ_DATABASE["crops"]["Groundnut"] = {"name_te": "వేరుశెనగ", "faqs": GROUNDNUT_FAQS}
FAQ_DATABASE["crops"]["Chilli"] = {"name_te": "మిర్చి", "faqs": CHILLI_FAQS}

# Count total FAQs
total = sum(len(c["faqs"]) for c in FAQ_DATABASE["crops"].values())
FAQ_DATABASE["total_faqs"] = total

# Save to file
output_path = r"c:\Users\hi\KisanMitra-AI-v2\backend\ml_engine\data\crop_faqs_complete.json"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(FAQ_DATABASE, f, indent=2, ensure_ascii=False)

print(f"✅ Created comprehensive FAQ database")
print(f"   Total FAQs: {total}")
for crop in FAQ_DATABASE["crops"]:
    print(f"   {crop}: {len(FAQ_DATABASE['crops'][crop]['faqs'])} FAQs")
